---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-parson-five
  labels:
    app: java-parson-five
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-parson-five
  template:
    metadata:
      labels:
        app: java-parson-five
    spec:
      containers:
        - name: java-parson-five
          image: docker.io/alexsotoharness/java-parson-five:latest
          ports:
            - containerPort: 8080