---
apiVersion: v1
kind: Service
metadata:
  name: java-parson-five-service
spec:
  selector:
    app: java-parson-five
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer